### ISSUE TITLE
The new version and the old version of your script doesn't work for me.

### ISSUE THREAD

**Issue by Tuxman2** [alesya-h/linux_detect_tablet_mode#10]
Hi,

I tried your new version (event mode) and your old version (accelerometer mode) but neither of them work :(

Each time I turn the laptop to 360 degrees nothing happens. I tried some of your commands in the terminal and nothing happens also (I don't have the message with tablet mode 1 or 0). I think I've got a big problem with lid switch. I also would like to know if your script can be used under wayland or not. 

Regards.

Note: test on Fedora 30 with 5.2.14 kernel on Medion Akoya convertible laptop.

More information about my hardware:

> $ xinput
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ xwayland-pointer:16                     	id=6	[slave  pointer  (2)]
⎜   ↳ xwayland-relative-pointer:16            	id=7	[slave  pointer  (2)]
⎜   ↳ xwayland-touch:16                       	id=9	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ xwayland-keyboard:16                    	id=8	[slave  keyboard (3)]

> $ sudo libinput list-devices

Event12 - HTIX5288:00 0911:5288 Touchpad: kernel bug: clickpad advertising right button
Device:           Video Bus
Kernel:           /dev/input/event8
Group:            1
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Lid Switch
Kernel:           /dev/input/event0
Group:            2
Seat:             seat0, default
Capabilities:     switch
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Power Button
Kernel:           /dev/input/event1
Group:            3
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           HDA Intel PCH Mic
Kernel:           /dev/input/event15
Group:            4
Seat:             seat0, default
Capabilities:     
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           HDA Intel PCH Front Headphone
Kernel:           /dev/input/event16
Group:            4
Seat:             seat0, default
Capabilities:     
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           HDA Intel PCH HDMI/DP,pcm=3
Kernel:           /dev/input/event17
Group:            4
Seat:             seat0, default
Capabilities:     
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           HDA Intel PCH HDMI/DP,pcm=7
Kernel:           /dev/input/event18
Group:            4
Seat:             seat0, default
Capabilities:     
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           HDA Intel PCH HDMI/DP,pcm=8
Kernel:           /dev/input/event19
Group:            4
Seat:             seat0, default
Capabilities:     
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           HDA Intel PCH HDMI/DP,pcm=9
Kernel:           /dev/input/event20
Group:            4
Seat:             seat0, default
Capabilities:     
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           HDA Intel PCH HDMI/DP,pcm=10
Kernel:           /dev/input/event21
Group:            4
Seat:             seat0, default
Capabilities:     
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           USB 2.0 Camera : USB 2.0 Camera
Kernel:           /dev/input/event13
Group:            6
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           FTSC1000:00 2808:5012
Kernel:           /dev/input/event11
Group:            7
Seat:             seat0, default
Size:             273x154mm
Capabilities:     touch 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      identity matrix
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           HTIX5288:00 0911:5288 Touchpad
Kernel:           /dev/input/event12
Group:            8
Seat:             seat0, default
Size:             93x60mm
Capabilities:     pointer gesture
Tap-to-click:     disabled
Tap-and-drag:     enabled
Tap drag lock:    disabled
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   *two-finger edge 
Click methods:    *button-areas clickfinger 
Disable-w-typing: enabled
Accel profiles:   none
Rotation:         n/a

Device:           Intel HID events
Kernel:           /dev/input/event9
Group:            9
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Intel HID 5 button array
Kernel:           /dev/input/event10
Group:            10
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           AT Translated Set 2 keyboard
Kernel:           /dev/input/event2
Group:            11
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

**Comment by alesguzik** [comment]
Both old and new scripts should work under wayland, though commands in the config would be different. Most likely they will be specific to your wayland compositor.

Does Windows detect your laptop switching to tablet mode and back?

**Comment by Tuxman2** [comment]
Hi Ales,

as xinitrc is for xorg, I don't know how to launch the "watch_tablet &" command under wayland. Do you know how to launch your script under wayland ?

Under Windows 10 the switching tablet mode works out-of-the-box. 

I will test Fedora 31(beta) because it have systemd243 and iio-proxy-sensor 2.8 version (new codes were added for the tablet switch mode). Perhaps your script will work with that Fedora version.

I'll keep you informed.

**Comment by Tuxman2** [comment]
Hi Ales,

well, I tested your old script version (with accelerometers support) on Fedora 31 beta (with : Kernel 5.3, Systemd 243 version, iio-proxy-sensor 2.8 version. So I have all the last versions). I'm on Gnome with the xorg session. 

1. I installed ruby package. Yaml is also installed.
2. I put your scripts files in /home/myuser/scripts/detect_tablet_mode folder.
3. I copied the watch_tablet.yml file in ~/.config/
4. I ajusted the config for my hardware (touchpad and keyboard).
5. I added watch_tablet & to my ~/.xinitrc file
6. I restarted my desktop session.

Despite this, my touchpad and my keyboard won't disable when I turn my laptop to 360 degrees. I also tried with the libinput debug-events command and nothing happens.

I don't know what's wrong. Accelerometer is working. 

Here are the information from /sys/bus/iio/devices folder : 

iio: device-0  
iio:device1

So it seems that I have two iio devices (probably two accelerometers).

Have you got an idea ?

Thanks.

**Comment by YamiYukiSenpai** [comment]
Did this work for you?

**Comment by alesya-h** [comment]
> as xinitrc is for xorg, I don't know how to launch the "watch_tablet &" command under wayland. Do you know how to launch your script under wayland ?

It depends on your compositor. If you are using a desktop environment like Gnome or KDE you can create a `detect-tablet-mode.desktop` file and add it to autostart (for Gnome open Gnome Tweaks app and go to the Startup Applications tab). For other  compositors you will need to check their documentation.

>  iio-proxy-sensor 2.8 version.

These scripts don't use iio-sensor-proxy and interact with accelerometer devices directly.

> Here are the information from /sys/bus/iio/devices folder :
> 
> iio: device-0
> iio:device1
> 
> So it seems that I have two iio devices (probably two accelerometers).

If there's just 2 iio devices most likely they are not accelerometers. To check it, just go to those device directories and look inside the `name` file - it should say `accel_3d`. Alternatively you can just run the `old/detect_accelerometers` and it will print the list of your accelerometer devices. If it prints nothing it means you don't have accelerometers available. 

From what I see your device just isn't supported.
