### ISSUE TITLE
configuration issue

### ISSUE THREAD

**Issue by thomarse-ef** [alesya-h/linux_detect_tablet_mode#14]
I'm trying to set up the config file. The command `stdbuf -oL libinput debug-events|grep switch` doesn't work on my machine (terminal just runs indefinitely no matter what I do with the laptop). `ls -lh /dev/input/by-path` output is:

    `total 0
    lrwxrwxrwx 1 root root  9 Apr 12 18:36 pci-0000:00:14.0-usb-0:5:1.0-event -> ../event7
    lrwxrwxrwx 1 root root  9 Apr 12 18:36 pci-0000:00:14.0-usb-0:5:1.2-event -> ../event8
    lrwxrwxrwx 1 root root 10 Apr 12 18:36 pci-0000:00:15.0-platform-i2c_designware.0-event -> ../event11
    lrwxrwxrwx 1 root root 10 Apr 12 18:36 pci-0000:00:15.0-platform-i2c_designware.0-event-mouse -> ../event16
    lrwxrwxrwx 1 root root  9 Apr 12 18:36 pci-0000:00:15.0-platform-i2c_designware.0-mouse -> ../mouse1
    lrwxrwxrwx 1 root root 10 Apr 12 18:36 pci-0000:00:15.1-platform-i2c_designware.1-event -> ../event15
    lrwxrwxrwx 1 root root 10 Apr 12 18:36 pci-0000:00:15.1-platform-i2c_designware.1-event-mouse -> ../event15
    lrwxrwxrwx 1 root root  9 Apr 12 18:36 pci-0000:00:15.1-platform-i2c_designware.1-mouse -> ../mouse3
    lrwxrwxrwx 1 root root  9 Apr 12 18:36 platform-i8042-serio-0-event-kbd -> ../event2
    lrwxrwxrwx 1 root root  9 Apr 12 18:36 platform-INT33D5:00-event -> ../event5
    lrwxrwxrwx 1 root root  9 Apr 12 18:36 platform-pcspkr-event-spkr -> ../event6`

I'm not sure what I'm meant to put as input_device?

Then I also don't know what to put in the next bit. I want to configure the onscreen keyboard to become active in tablet mode and then to turn off in laptop mode. I've searched but can't find the command to switch the onscreen keyboard on. Any idea how to do this?

FYI I'm running Manjaro Gnome and installed the package from AUR. 

Thanks.

**Comment by alesya-h** [comment]
If `stdbuf -oL libinput debug-events|grep switch` doesn't return anything, your device is not supported.
