### ISSUE TITLE
stdbuf -oL libinput debug-events|grep switch doesnt return anything

### ISSUE THREAD

**Issue by BoaTheCrafter** [alesya-h/linux_detect_tablet_mode#21]
Hi there, thanks for your project, but i've gotten a weird issue when trying to get it to work on my machine (Lenovo Yoga 530-14ikb) with the current Pop_OS! Version 21.04 and GNOME 3.38.5:

The command you listet for checking the libinput debug-events just doesnt work. I enter it in my Terminal and it doesnt return anything. I tried flipping my screen while the command is running, but even this has the same issue. 
And since i'm not sure, which event (ls -lh /dev/input/by-path lists like 7 or 8 different inputs with only the keyboard being similiar named to your example config) is needed for my device, i cant get the script to work.

Did you already stumble upon this issue with the aforementioned command?

**Comment by alesya-h** [comment]
If it doesn't return anything it just means that your device is not supported. I've updated the README to clarify how to check if your device is supported.
