### ISSUE TITLE
Pls help

### ISSUE THREAD

**Issue by TylerHelt0** [alesya-h/linux_detect_tablet_mode#28]
Any idea why the media keys on the Gen1 X1 Yoga are all of a sudden firing off the same acpi event as the lid switch (8)? It used to work as expected a few months ago before an incremental kernel upgrade on from 5.15.5x to 5.15.63 but now when I press any of the media keys from f6 to f12 tablet mode is activated. This doesn't  happen with the normal f6-f12. 

I also accidentally removed my kde desktop before this began to happen but messing with kde shortcuts does not solve the issue. The key performs the shortcut and still activates tablet mode. 

Is it related to tp_smapi?

**Comment by alesya-h** [comment]
This project's issues are not a support forum.
